<?xml version="1.0" encoding="utf-8"?><Database Name="Food" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Food.mdf;Integrated Security=True" SettingsObjectName="Ccounter_gurami_oop.Properties.Settings" SettingsPropertyName="FoodConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Table]" Member="Tables">
    <Type Name="Table">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Calories" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>